// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: onomyprotocol/gnark/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryCircuitRequest struct {
	CircuitId string `protobuf:"bytes,1,opt,name=circuit_id,json=circuitId,proto3" json:"circuit_id,omitempty"`
}

func (m *QueryCircuitRequest) Reset()         { *m = QueryCircuitRequest{} }
func (m *QueryCircuitRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCircuitRequest) ProtoMessage()    {}
func (*QueryCircuitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b573bb45d19673cc, []int{0}
}
func (m *QueryCircuitRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCircuitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCircuitRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCircuitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCircuitRequest.Merge(m, src)
}
func (m *QueryCircuitRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCircuitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCircuitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCircuitRequest proto.InternalMessageInfo

func (m *QueryCircuitRequest) GetCircuitId() string {
	if m != nil {
		return m.CircuitId
	}
	return ""
}

type QueryCircuitResponse struct {
	Circuit *Circuit `protobuf:"bytes,1,opt,name=circuit,proto3" json:"circuit,omitempty"`
}

func (m *QueryCircuitResponse) Reset()         { *m = QueryCircuitResponse{} }
func (m *QueryCircuitResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCircuitResponse) ProtoMessage()    {}
func (*QueryCircuitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b573bb45d19673cc, []int{1}
}
func (m *QueryCircuitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCircuitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCircuitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCircuitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCircuitResponse.Merge(m, src)
}
func (m *QueryCircuitResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCircuitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCircuitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCircuitResponse proto.InternalMessageInfo

func (m *QueryCircuitResponse) GetCircuit() *Circuit {
	if m != nil {
		return m.Circuit
	}
	return nil
}

type QueryCircuitsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryCircuitsRequest) Reset()         { *m = QueryCircuitsRequest{} }
func (m *QueryCircuitsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCircuitsRequest) ProtoMessage()    {}
func (*QueryCircuitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b573bb45d19673cc, []int{2}
}
func (m *QueryCircuitsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCircuitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCircuitsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCircuitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCircuitsRequest.Merge(m, src)
}
func (m *QueryCircuitsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCircuitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCircuitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCircuitsRequest proto.InternalMessageInfo

func (m *QueryCircuitsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryCircuitsResponse struct {
	Circuits   []Circuit           `protobuf:"bytes,1,rep,name=circuits,proto3" json:"circuits"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryCircuitsResponse) Reset()         { *m = QueryCircuitsResponse{} }
func (m *QueryCircuitsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCircuitsResponse) ProtoMessage()    {}
func (*QueryCircuitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b573bb45d19673cc, []int{3}
}
func (m *QueryCircuitsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCircuitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCircuitsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCircuitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCircuitsResponse.Merge(m, src)
}
func (m *QueryCircuitsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCircuitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCircuitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCircuitsResponse proto.InternalMessageInfo

func (m *QueryCircuitsResponse) GetCircuits() []Circuit {
	if m != nil {
		return m.Circuits
	}
	return nil
}

func (m *QueryCircuitsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryCircuitRequest)(nil), "onomyprotocol.gnark.v1.QueryCircuitRequest")
	proto.RegisterType((*QueryCircuitResponse)(nil), "onomyprotocol.gnark.v1.QueryCircuitResponse")
	proto.RegisterType((*QueryCircuitsRequest)(nil), "onomyprotocol.gnark.v1.QueryCircuitsRequest")
	proto.RegisterType((*QueryCircuitsResponse)(nil), "onomyprotocol.gnark.v1.QueryCircuitsResponse")
}

func init() {
	proto.RegisterFile("onomyprotocol/gnark/v1/query.proto", fileDescriptor_b573bb45d19673cc)
}

var fileDescriptor_b573bb45d19673cc = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xbf, 0xae, 0xd3, 0x30,
	0x14, 0xc6, 0xe3, 0xf2, 0xe7, 0xde, 0x6b, 0x36, 0x73, 0x41, 0x55, 0x04, 0xb9, 0x55, 0x24, 0x28,
	0x82, 0xd6, 0x56, 0x0a, 0x0b, 0x23, 0x45, 0x2a, 0x62, 0xa3, 0x19, 0x19, 0x40, 0x4e, 0x6a, 0x99,
	0x88, 0x36, 0x4e, 0x63, 0xa7, 0xa2, 0x42, 0x2c, 0x6c, 0x6c, 0x48, 0x7d, 0x04, 0x26, 0xde, 0xa4,
	0x63, 0x25, 0x16, 0x26, 0x84, 0x5a, 0x1e, 0x04, 0xd5, 0x76, 0x68, 0x83, 0x5a, 0xdd, 0x6c, 0xd1,
	0x39, 0xe7, 0x3b, 0xdf, 0xcf, 0x9f, 0x1d, 0xe8, 0x8b, 0x54, 0x4c, 0xe6, 0x59, 0x2e, 0x94, 0x88,
	0xc5, 0x98, 0xf0, 0x94, 0xe6, 0xef, 0xc9, 0x2c, 0x20, 0xd3, 0x82, 0xe5, 0x73, 0xac, 0xeb, 0xe8,
	0x76, 0x65, 0x06, 0xeb, 0x19, 0x3c, 0x0b, 0xdc, 0x87, 0xb1, 0x90, 0x13, 0x21, 0x49, 0x44, 0x25,
	0x33, 0x02, 0x32, 0x0b, 0x22, 0xa6, 0x68, 0x40, 0x32, 0xca, 0x93, 0x94, 0xaa, 0x44, 0xa4, 0x66,
	0x87, 0x7b, 0x87, 0x0b, 0xc1, 0xc7, 0x8c, 0xd0, 0x2c, 0x21, 0x34, 0x4d, 0x85, 0xd2, 0x4d, 0x69,
	0xbb, 0xe7, 0x5c, 0x70, 0xa1, 0x3f, 0xc9, 0xf6, 0xcb, 0x56, 0x8f, 0xb1, 0x19, 0x00, 0x5d, 0xf7,
	0x9f, 0xc0, 0x9b, 0xc3, 0xad, 0xf3, 0xf3, 0x24, 0x8f, 0x8b, 0x44, 0x85, 0x6c, 0x5a, 0x30, 0xa9,
	0xd0, 0x5d, 0x08, 0x63, 0x53, 0x79, 0x9b, 0x8c, 0x9a, 0xa0, 0x05, 0x1e, 0x9c, 0x85, 0x67, 0xb6,
	0xf2, 0x72, 0xe4, 0x0f, 0xe1, 0x79, 0x55, 0x25, 0x33, 0x91, 0x4a, 0x86, 0x9e, 0xc2, 0x13, 0x3b,
	0xa4, 0x35, 0x37, 0x7a, 0x17, 0xf8, 0xf0, 0xd9, 0x71, 0xa9, 0x2c, 0xe7, 0xfd, 0x37, 0xd5, 0x95,
	0xb2, 0x24, 0x19, 0x40, 0xb8, 0x0b, 0xc3, 0x6e, 0xbd, 0x8f, 0x4d, 0x72, 0x78, 0x9b, 0x1c, 0x36,
	0x51, 0xdb, 0xe4, 0xf0, 0x2b, 0xca, 0x99, 0xd5, 0x86, 0x7b, 0x4a, 0xff, 0x1b, 0x80, 0xb7, 0xfe,
	0x33, 0xb0, 0xd0, 0xcf, 0xe0, 0xa9, 0x85, 0x90, 0x4d, 0xd0, 0xba, 0x52, 0x83, 0xba, 0x7f, 0x75,
	0xf9, 0xeb, 0xc2, 0x09, 0xff, 0xc9, 0xd0, 0x8b, 0x0a, 0x64, 0x43, 0x43, 0xb6, 0x2f, 0x85, 0x34,
	0xfe, 0xfb, 0x94, 0xbd, 0xef, 0x0d, 0x78, 0x4d, 0x53, 0xa2, 0x05, 0x80, 0x27, 0xd6, 0x0e, 0x3d,
	0x3a, 0xc6, 0x73, 0xe0, 0xea, 0xdc, 0x4e, 0xbd, 0x61, 0x63, 0xee, 0x77, 0x3f, 0xff, 0xf8, 0xb3,
	0x68, 0xb4, 0xd1, 0x3d, 0xa2, 0x55, 0xbb, 0x47, 0x52, 0x9e, 0x8d, 0x7c, 0xdc, 0x3d, 0x84, 0x4f,
	0xe8, 0x0b, 0x80, 0xa7, 0x65, 0x80, 0xa8, 0x96, 0x53, 0x79, 0x91, 0x6e, 0xb7, 0xe6, 0xb4, 0x05,
	0x6b, 0x69, 0x30, 0x17, 0x35, 0x8f, 0x81, 0xf5, 0x07, 0xcb, 0xb5, 0x07, 0x56, 0x6b, 0x0f, 0xfc,
	0x5e, 0x7b, 0xe0, 0xeb, 0xc6, 0x73, 0x56, 0x1b, 0xcf, 0xf9, 0xb9, 0xf1, 0x9c, 0xd7, 0x1d, 0x9e,
	0xa8, 0x77, 0x45, 0x84, 0x63, 0x31, 0x21, 0xd5, 0x7f, 0xc0, 0xec, 0xfa, 0x60, 0xb7, 0xa9, 0x79,
	0xc6, 0x64, 0x74, 0x5d, 0x77, 0x1f, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x40, 0xa6, 0x3f, 0xff,
	0xcb, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Circuit returns the stored circuit for a given identifier.
	Circuit(ctx context.Context, in *QueryCircuitRequest, opts ...grpc.CallOption) (*QueryCircuitResponse, error)
	// Circuits lists all circuits with pagination support.
	Circuits(ctx context.Context, in *QueryCircuitsRequest, opts ...grpc.CallOption) (*QueryCircuitsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Circuit(ctx context.Context, in *QueryCircuitRequest, opts ...grpc.CallOption) (*QueryCircuitResponse, error) {
	out := new(QueryCircuitResponse)
	err := c.cc.Invoke(ctx, "/onomyprotocol.gnark.v1.Query/Circuit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Circuits(ctx context.Context, in *QueryCircuitsRequest, opts ...grpc.CallOption) (*QueryCircuitsResponse, error) {
	out := new(QueryCircuitsResponse)
	err := c.cc.Invoke(ctx, "/onomyprotocol.gnark.v1.Query/Circuits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Circuit returns the stored circuit for a given identifier.
	Circuit(context.Context, *QueryCircuitRequest) (*QueryCircuitResponse, error)
	// Circuits lists all circuits with pagination support.
	Circuits(context.Context, *QueryCircuitsRequest) (*QueryCircuitsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Circuit(ctx context.Context, req *QueryCircuitRequest) (*QueryCircuitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Circuit not implemented")
}
func (*UnimplementedQueryServer) Circuits(ctx context.Context, req *QueryCircuitsRequest) (*QueryCircuitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Circuits not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Circuit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCircuitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Circuit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onomyprotocol.gnark.v1.Query/Circuit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Circuit(ctx, req.(*QueryCircuitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Circuits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCircuitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Circuits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onomyprotocol.gnark.v1.Query/Circuits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Circuits(ctx, req.(*QueryCircuitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onomyprotocol.gnark.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Circuit",
			Handler:    _Query_Circuit_Handler,
		},
		{
			MethodName: "Circuits",
			Handler:    _Query_Circuits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "onomyprotocol/gnark/v1/query.proto",
}

func (m *QueryCircuitRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCircuitRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCircuitRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CircuitId) > 0 {
		i -= len(m.CircuitId)
		copy(dAtA[i:], m.CircuitId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CircuitId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCircuitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCircuitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCircuitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Circuit != nil {
		{
			size, err := m.Circuit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCircuitsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCircuitsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCircuitsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCircuitsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCircuitsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCircuitsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Circuits) > 0 {
		for iNdEx := len(m.Circuits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Circuits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryCircuitRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CircuitId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCircuitResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Circuit != nil {
		l = m.Circuit.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCircuitsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCircuitsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Circuits) > 0 {
		for _, e := range m.Circuits {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryCircuitRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCircuitRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCircuitRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CircuitId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CircuitId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCircuitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCircuitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCircuitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Circuit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Circuit == nil {
				m.Circuit = &Circuit{}
			}
			if err := m.Circuit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCircuitsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCircuitsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCircuitsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCircuitsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCircuitsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCircuitsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Circuits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Circuits = append(m.Circuits, Circuit{})
			if err := m.Circuits[len(m.Circuits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
