// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: onomyprotocol/gnark/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateCircuit struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	CircuitId    string `protobuf:"bytes,2,opt,name=circuit_id,json=circuitId,proto3" json:"circuit_id,omitempty"`
	CurveId      string `protobuf:"bytes,3,opt,name=curve_id,json=curveId,proto3" json:"curve_id,omitempty"`
	VerifyingKey []byte `protobuf:"bytes,4,opt,name=verifying_key,json=verifyingKey,proto3" json:"verifying_key,omitempty"`
	Circuit      []byte `protobuf:"bytes,5,opt,name=circuit,proto3" json:"circuit,omitempty"`
}

func (m *MsgCreateCircuit) Reset()         { *m = MsgCreateCircuit{} }
func (m *MsgCreateCircuit) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCircuit) ProtoMessage()    {}
func (*MsgCreateCircuit) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7928b0e1f3d4b47, []int{0}
}
func (m *MsgCreateCircuit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCircuit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCircuit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCircuit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCircuit.Merge(m, src)
}
func (m *MsgCreateCircuit) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCircuit) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCircuit.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCircuit proto.InternalMessageInfo

type MsgCreateCircuitResponse struct {
}

func (m *MsgCreateCircuitResponse) Reset()         { *m = MsgCreateCircuitResponse{} }
func (m *MsgCreateCircuitResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCircuitResponse) ProtoMessage()    {}
func (*MsgCreateCircuitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7928b0e1f3d4b47, []int{1}
}
func (m *MsgCreateCircuitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCircuitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCircuitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCircuitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCircuitResponse.Merge(m, src)
}
func (m *MsgCreateCircuitResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCircuitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCircuitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCircuitResponse proto.InternalMessageInfo

type MsgVerifyProof struct {
	Creator       string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	CircuitId     string `protobuf:"bytes,2,opt,name=circuit_id,json=circuitId,proto3" json:"circuit_id,omitempty"`
	Proof         []byte `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	PublicWitness []byte `protobuf:"bytes,4,opt,name=public_witness,json=publicWitness,proto3" json:"public_witness,omitempty"`
}

func (m *MsgVerifyProof) Reset()         { *m = MsgVerifyProof{} }
func (m *MsgVerifyProof) String() string { return proto.CompactTextString(m) }
func (*MsgVerifyProof) ProtoMessage()    {}
func (*MsgVerifyProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7928b0e1f3d4b47, []int{2}
}
func (m *MsgVerifyProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVerifyProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVerifyProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVerifyProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVerifyProof.Merge(m, src)
}
func (m *MsgVerifyProof) XXX_Size() int {
	return m.Size()
}
func (m *MsgVerifyProof) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVerifyProof.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVerifyProof proto.InternalMessageInfo

type MsgVerifyProofResponse struct {
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (m *MsgVerifyProofResponse) Reset()         { *m = MsgVerifyProofResponse{} }
func (m *MsgVerifyProofResponse) String() string { return proto.CompactTextString(m) }
func (*MsgVerifyProofResponse) ProtoMessage()    {}
func (*MsgVerifyProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7928b0e1f3d4b47, []int{3}
}
func (m *MsgVerifyProofResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVerifyProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVerifyProofResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVerifyProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVerifyProofResponse.Merge(m, src)
}
func (m *MsgVerifyProofResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgVerifyProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVerifyProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVerifyProofResponse proto.InternalMessageInfo

func (m *MsgVerifyProofResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*MsgCreateCircuit)(nil), "onomyprotocol.gnark.v1.MsgCreateCircuit")
	proto.RegisterType((*MsgCreateCircuitResponse)(nil), "onomyprotocol.gnark.v1.MsgCreateCircuitResponse")
	proto.RegisterType((*MsgVerifyProof)(nil), "onomyprotocol.gnark.v1.MsgVerifyProof")
	proto.RegisterType((*MsgVerifyProofResponse)(nil), "onomyprotocol.gnark.v1.MsgVerifyProofResponse")
}

func init() { proto.RegisterFile("onomyprotocol/gnark/v1/tx.proto", fileDescriptor_e7928b0e1f3d4b47) }

var fileDescriptor_e7928b0e1f3d4b47 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xde, 0x49, 0x8d, 0xb6, 0x63, 0x52, 0x64, 0x09, 0x75, 0x5d, 0xec, 0xa6, 0x6c, 0x51, 0x42,
	0x28, 0x3b, 0x46, 0x0f, 0x42, 0x8e, 0x16, 0x84, 0x22, 0x01, 0xd9, 0x83, 0x82, 0x97, 0xb0, 0xd9,
	0x4c, 0xc7, 0xa1, 0xd9, 0x7d, 0xcb, 0xce, 0x64, 0xed, 0x22, 0x82, 0xf4, 0xe4, 0xb1, 0xe0, 0x55,
	0xa4, 0x3f, 0xa1, 0x77, 0x2f, 0x1e, 0x3d, 0x16, 0xbc, 0x78, 0x94, 0x44, 0xa8, 0x3f, 0x43, 0x76,
	0x66, 0x93, 0x36, 0xc5, 0x4a, 0xf1, 0xb6, 0xef, 0x7b, 0xdf, 0x7b, 0xdf, 0xf7, 0xde, 0xbc, 0xc5,
	0x4d, 0x88, 0x21, 0xca, 0x93, 0x14, 0x24, 0x84, 0x30, 0x22, 0x2c, 0x0e, 0xd2, 0x3d, 0x92, 0x75,
	0x88, 0xdc, 0xf7, 0x14, 0x68, 0xae, 0x2d, 0x10, 0x3c, 0x45, 0xf0, 0xb2, 0x8e, 0x7d, 0x3b, 0x04,
	0x11, 0x81, 0x20, 0x91, 0x60, 0x05, 0x3f, 0x12, 0x4c, 0x17, 0xd8, 0x0d, 0x06, 0x0c, 0xd4, 0x27,
	0x29, 0xbe, 0x4a, 0xf4, 0x2e, 0x03, 0x60, 0x23, 0x4a, 0x82, 0x84, 0x93, 0x20, 0x8e, 0x41, 0x06,
	0x92, 0x43, 0x2c, 0x74, 0xd6, 0xfd, 0x82, 0xf0, 0xad, 0x9e, 0x60, 0xdb, 0x29, 0x0d, 0x24, 0xdd,
	0xe6, 0x69, 0x38, 0xe6, 0xd2, 0xb4, 0xf0, 0x8d, 0xb0, 0x00, 0x20, 0xb5, 0xd0, 0x06, 0x6a, 0xad,
	0xf8, 0xb3, 0xd0, 0x5c, 0xc7, 0x38, 0xd4, 0xa4, 0x3e, 0x1f, 0x5a, 0x15, 0x95, 0x5c, 0x29, 0x91,
	0x9d, 0xa1, 0x79, 0x07, 0x2f, 0x87, 0xe3, 0x34, 0xa3, 0x45, 0x72, 0xa9, 0xac, 0x2c, 0xe2, 0x9d,
	0xa1, 0xb9, 0x89, 0xeb, 0x19, 0x4d, 0xf9, 0x6e, 0xce, 0x63, 0xd6, 0xdf, 0xa3, 0xb9, 0x75, 0x6d,
	0x03, 0xb5, 0x6a, 0x7e, 0x6d, 0x0e, 0x3e, 0xa3, 0xb9, 0x12, 0xd6, 0xcd, 0xac, 0xaa, 0x4a, 0xcf,
	0xc2, 0x6e, 0xe3, 0xc3, 0x51, 0xd3, 0xf8, 0x7d, 0xd4, 0x34, 0x0e, 0x4e, 0x8f, 0xdb, 0x33, 0x3b,
	0xae, 0x8d, 0xad, 0x8b, 0xe6, 0x7d, 0x2a, 0x12, 0x88, 0x05, 0x75, 0x3f, 0x21, 0xbc, 0xda, 0x13,
	0xec, 0x85, 0xea, 0xff, 0x3c, 0x05, 0xd8, 0xfd, 0xff, 0xb9, 0x1a, 0xb8, 0x9a, 0x14, 0x1d, 0xd4,
	0x50, 0x35, 0x5f, 0x07, 0xe6, 0x3d, 0xbc, 0x9a, 0x8c, 0x07, 0x23, 0x1e, 0xf6, 0xdf, 0x70, 0x19,
	0x53, 0x21, 0xca, 0x99, 0xea, 0x1a, 0x7d, 0xa9, 0xc1, 0x4b, 0xac, 0x7b, 0x78, 0x6d, 0xd1, 0xdd,
	0xcc, 0x78, 0x21, 0x96, 0x05, 0x23, 0x3e, 0x54, 0x1e, 0x97, 0x7d, 0x1d, 0x3c, 0xfc, 0x5a, 0xc1,
	0x4b, 0x3d, 0xc1, 0xcc, 0x43, 0x84, 0xeb, 0x8b, 0xaf, 0xd5, 0xf2, 0xfe, 0x7e, 0x28, 0xde, 0xc5,
	0xd5, 0xd8, 0x0f, 0xae, 0xca, 0x9c, 0x2f, 0x71, 0xf3, 0xe0, 0xfb, 0xaf, 0x8f, 0x95, 0x75, 0xd7,
	0x22, 0xaa, 0xf2, 0xec, 0x4a, 0xcb, 0xdd, 0x88, 0x2e, 0x6a, 0x9b, 0x9f, 0x11, 0xbe, 0x79, 0x7e,
	0xcd, 0xf7, 0xff, 0x21, 0x73, 0x8e, 0x67, 0x7b, 0x57, 0xe3, 0xcd, 0xcd, 0x3c, 0x56, 0x66, 0x3a,
	0xee, 0xd6, 0x65, 0x66, 0xc8, 0xdb, 0xb3, 0x47, 0x7c, 0xd7, 0xd5, 0x97, 0xd5, 0x45, 0x6d, 0xbb,
	0xfa, 0xfe, 0xf4, 0xb8, 0x8d, 0x9e, 0x3c, 0xfd, 0x36, 0x71, 0xd0, 0xc9, 0xc4, 0x41, 0x3f, 0x27,
	0x0e, 0x3a, 0x9c, 0x3a, 0xc6, 0xc9, 0xd4, 0x31, 0x7e, 0x4c, 0x1d, 0xe3, 0xd5, 0x16, 0xe3, 0xf2,
	0xf5, 0x78, 0xe0, 0x85, 0x10, 0x91, 0xc5, 0xdf, 0x52, 0x2b, 0xed, 0x97, 0x5a, 0x32, 0x4f, 0xa8,
	0x18, 0x5c, 0x57, 0xd9, 0x47, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x40, 0x01, 0x43, 0xc1, 0xc2,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// CreateCircuit uploads a verifying key and circuit definition onto the chain.
	CreateCircuit(ctx context.Context, in *MsgCreateCircuit, opts ...grpc.CallOption) (*MsgCreateCircuitResponse, error)
	// VerifyProof checks a proof against a stored circuit and verifying key.
	VerifyProof(ctx context.Context, in *MsgVerifyProof, opts ...grpc.CallOption) (*MsgVerifyProofResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateCircuit(ctx context.Context, in *MsgCreateCircuit, opts ...grpc.CallOption) (*MsgCreateCircuitResponse, error) {
	out := new(MsgCreateCircuitResponse)
	err := c.cc.Invoke(ctx, "/onomyprotocol.gnark.v1.Msg/CreateCircuit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) VerifyProof(ctx context.Context, in *MsgVerifyProof, opts ...grpc.CallOption) (*MsgVerifyProofResponse, error) {
	out := new(MsgVerifyProofResponse)
	err := c.cc.Invoke(ctx, "/onomyprotocol.gnark.v1.Msg/VerifyProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// CreateCircuit uploads a verifying key and circuit definition onto the chain.
	CreateCircuit(context.Context, *MsgCreateCircuit) (*MsgCreateCircuitResponse, error)
	// VerifyProof checks a proof against a stored circuit and verifying key.
	VerifyProof(context.Context, *MsgVerifyProof) (*MsgVerifyProofResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateCircuit(ctx context.Context, req *MsgCreateCircuit) (*MsgCreateCircuitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCircuit not implemented")
}
func (*UnimplementedMsgServer) VerifyProof(ctx context.Context, req *MsgVerifyProof) (*MsgVerifyProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyProof not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateCircuit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateCircuit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateCircuit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onomyprotocol.gnark.v1.Msg/CreateCircuit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateCircuit(ctx, req.(*MsgCreateCircuit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_VerifyProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgVerifyProof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).VerifyProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onomyprotocol.gnark.v1.Msg/VerifyProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).VerifyProof(ctx, req.(*MsgVerifyProof))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onomyprotocol.gnark.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCircuit",
			Handler:    _Msg_CreateCircuit_Handler,
		},
		{
			MethodName: "VerifyProof",
			Handler:    _Msg_VerifyProof_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "onomyprotocol/gnark/v1/tx.proto",
}

func (m *MsgCreateCircuit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCircuit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCircuit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Circuit) > 0 {
		i -= len(m.Circuit)
		copy(dAtA[i:], m.Circuit)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Circuit)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.VerifyingKey) > 0 {
		i -= len(m.VerifyingKey)
		copy(dAtA[i:], m.VerifyingKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.VerifyingKey)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.CurveId) > 0 {
		i -= len(m.CurveId)
		copy(dAtA[i:], m.CurveId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CurveId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CircuitId) > 0 {
		i -= len(m.CircuitId)
		copy(dAtA[i:], m.CircuitId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CircuitId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateCircuitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCircuitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCircuitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgVerifyProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVerifyProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVerifyProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PublicWitness) > 0 {
		i -= len(m.PublicWitness)
		copy(dAtA[i:], m.PublicWitness)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PublicWitness)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CircuitId) > 0 {
		i -= len(m.CircuitId)
		copy(dAtA[i:], m.CircuitId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CircuitId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgVerifyProofResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVerifyProofResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVerifyProofResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Valid {
		i--
		if m.Valid {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateCircuit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CircuitId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CurveId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.VerifyingKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Circuit)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateCircuitResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgVerifyProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CircuitId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PublicWitness)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgVerifyProofResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Valid {
		n += 2
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateCircuit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCircuit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCircuit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CircuitId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CircuitId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurveId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurveId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifyingKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerifyingKey = append(m.VerifyingKey[:0], dAtA[iNdEx:postIndex]...)
			if m.VerifyingKey == nil {
				m.VerifyingKey = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Circuit", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Circuit = append(m.Circuit[:0], dAtA[iNdEx:postIndex]...)
			if m.Circuit == nil {
				m.Circuit = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCircuitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCircuitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCircuitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVerifyProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVerifyProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVerifyProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CircuitId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CircuitId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Proof == nil {
				m.Proof = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicWitness", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicWitness = append(m.PublicWitness[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicWitness == nil {
				m.PublicWitness = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVerifyProofResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVerifyProofResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVerifyProofResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Valid", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Valid = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
