// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: onomyprotocol/psm/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSwapToIST struct {
	Address string      `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Coin    *types.Coin `protobuf:"bytes,2,opt,name=coin,proto3" json:"coin,omitempty"`
}

func (m *MsgSwapToIST) Reset()         { *m = MsgSwapToIST{} }
func (m *MsgSwapToIST) String() string { return proto.CompactTextString(m) }
func (*MsgSwapToIST) ProtoMessage()    {}
func (*MsgSwapToIST) Descriptor() ([]byte, []int) {
	return fileDescriptor_e309b5fc4e6d7e5a, []int{0}
}
func (m *MsgSwapToIST) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSwapToIST) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSwapToIST.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSwapToIST) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSwapToIST.Merge(m, src)
}
func (m *MsgSwapToIST) XXX_Size() int {
	return m.Size()
}
func (m *MsgSwapToIST) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSwapToIST.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSwapToIST proto.InternalMessageInfo

func (m *MsgSwapToIST) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgSwapToIST) GetCoin() *types.Coin {
	if m != nil {
		return m.Coin
	}
	return nil
}

type MsgSwapToISTResponse struct {
}

func (m *MsgSwapToISTResponse) Reset()         { *m = MsgSwapToISTResponse{} }
func (m *MsgSwapToISTResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSwapToISTResponse) ProtoMessage()    {}
func (*MsgSwapToISTResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e309b5fc4e6d7e5a, []int{1}
}
func (m *MsgSwapToISTResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSwapToISTResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSwapToISTResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSwapToISTResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSwapToISTResponse.Merge(m, src)
}
func (m *MsgSwapToISTResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSwapToISTResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSwapToISTResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSwapToISTResponse proto.InternalMessageInfo

type MsgSwapToStablecoin struct {
	Address string                                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ToDenom string                                 `protobuf:"bytes,2,opt,name=to_denom,json=toDenom,proto3" json:"to_denom,omitempty"`
	Amount  github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount" yaml:"pool_rate"`
}

func (m *MsgSwapToStablecoin) Reset()         { *m = MsgSwapToStablecoin{} }
func (m *MsgSwapToStablecoin) String() string { return proto.CompactTextString(m) }
func (*MsgSwapToStablecoin) ProtoMessage()    {}
func (*MsgSwapToStablecoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_e309b5fc4e6d7e5a, []int{2}
}
func (m *MsgSwapToStablecoin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSwapToStablecoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSwapToStablecoin.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSwapToStablecoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSwapToStablecoin.Merge(m, src)
}
func (m *MsgSwapToStablecoin) XXX_Size() int {
	return m.Size()
}
func (m *MsgSwapToStablecoin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSwapToStablecoin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSwapToStablecoin proto.InternalMessageInfo

func (m *MsgSwapToStablecoin) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgSwapToStablecoin) GetToDenom() string {
	if m != nil {
		return m.ToDenom
	}
	return ""
}

type MsgSwapToStablecoinResponse struct {
}

func (m *MsgSwapToStablecoinResponse) Reset()         { *m = MsgSwapToStablecoinResponse{} }
func (m *MsgSwapToStablecoinResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSwapToStablecoinResponse) ProtoMessage()    {}
func (*MsgSwapToStablecoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e309b5fc4e6d7e5a, []int{3}
}
func (m *MsgSwapToStablecoinResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSwapToStablecoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSwapToStablecoinResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSwapToStablecoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSwapToStablecoinResponse.Merge(m, src)
}
func (m *MsgSwapToStablecoinResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSwapToStablecoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSwapToStablecoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSwapToStablecoinResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSwapToIST)(nil), "onomyprotocol.psm.v1.MsgSwapToIST")
	proto.RegisterType((*MsgSwapToISTResponse)(nil), "onomyprotocol.psm.v1.MsgSwapToISTResponse")
	proto.RegisterType((*MsgSwapToStablecoin)(nil), "onomyprotocol.psm.v1.MsgSwapToStablecoin")
	proto.RegisterType((*MsgSwapToStablecoinResponse)(nil), "onomyprotocol.psm.v1.MsgSwapToStablecoinResponse")
}

func init() { proto.RegisterFile("onomyprotocol/psm/v1/tx.proto", fileDescriptor_e309b5fc4e6d7e5a) }

var fileDescriptor_e309b5fc4e6d7e5a = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0x3d, 0x14, 0xb5, 0x64, 0xe8, 0xa2, 0x32, 0x11, 0x72, 0x8d, 0xea, 0x44, 0x5e, 0x20,
	0x83, 0xd4, 0x19, 0xb9, 0xec, 0x58, 0x1a, 0x36, 0x5d, 0x74, 0xe3, 0x54, 0x42, 0x2a, 0x8b, 0x6a,
	0x6c, 0x0f, 0xc6, 0xc2, 0xe3, 0x37, 0xf2, 0x8c, 0x43, 0x73, 0x0b, 0x4e, 0xc1, 0x59, 0xba, 0xec,
	0x82, 0x05, 0x62, 0x11, 0xa1, 0xe4, 0x06, 0x9c, 0x00, 0x79, 0x12, 0x37, 0x41, 0x44, 0x49, 0x57,
	0xf6, 0x7b, 0xff, 0xef, 0xf7, 0x3d, 0xff, 0x33, 0xf8, 0x04, 0x2a, 0x10, 0x13, 0x59, 0x83, 0x86,
	0x14, 0x4a, 0x2a, 0x95, 0xa0, 0xe3, 0x90, 0xea, 0x1b, 0x62, 0x5a, 0x76, 0xff, 0x1f, 0x99, 0x48,
	0x25, 0xc8, 0x38, 0x74, 0xfb, 0x39, 0xe4, 0x60, 0x9a, 0xb4, 0x7d, 0x5b, 0x78, 0x5d, 0x2f, 0x07,
	0xc8, 0x4b, 0x4e, 0x4d, 0x95, 0x34, 0x9f, 0x68, 0xd6, 0xd4, 0x4c, 0x17, 0x50, 0x75, 0x7a, 0x0a,
	0x4a, 0x80, 0xa2, 0x09, 0x53, 0x9c, 0x8e, 0xc3, 0x84, 0x6b, 0x16, 0xd2, 0x14, 0x8a, 0x7b, 0x7d,
	0xe3, 0x2a, 0x2d, 0xd2, 0xf4, 0xfc, 0x0f, 0xf8, 0xf0, 0x42, 0xe5, 0xa3, 0xaf, 0x4c, 0x5e, 0xc2,
	0xf9, 0xe8, 0xd2, 0x76, 0xf0, 0x01, 0xcb, 0xb2, 0x9a, 0x2b, 0xe5, 0xa0, 0x21, 0x0a, 0x7a, 0x71,
	0x57, 0xda, 0xa7, 0xf8, 0x71, 0x3b, 0xd7, 0x79, 0x34, 0x44, 0xc1, 0xd3, 0xb3, 0x63, 0xb2, 0x00,
	0x93, 0x16, 0x4c, 0x96, 0x60, 0xf2, 0x0e, 0x8a, 0x2a, 0x36, 0x36, 0xff, 0x39, 0xee, 0xaf, 0x0f,
	0x8e, 0xb9, 0x92, 0x50, 0x29, 0xee, 0x7f, 0x47, 0xf8, 0xd9, 0xbd, 0x30, 0xd2, 0x2c, 0x29, 0x79,
	0xeb, 0xdf, 0x02, 0x3e, 0xc6, 0x4f, 0x34, 0x5c, 0x67, 0xbc, 0x02, 0x61, 0xe0, 0xbd, 0xf8, 0x40,
	0xc3, 0xfb, 0xb6, 0xb4, 0xaf, 0xf0, 0x3e, 0x13, 0xd0, 0x54, 0xda, 0xd9, 0x1b, 0xa2, 0xe0, 0x30,
	0x8a, 0x6e, 0xa7, 0x03, 0xeb, 0xd7, 0x74, 0xf0, 0x32, 0x2f, 0xf4, 0xe7, 0x26, 0x21, 0x29, 0x08,
	0xba, 0x0c, 0x68, 0xf1, 0x38, 0x55, 0xd9, 0x17, 0xaa, 0x27, 0x92, 0x2b, 0x72, 0x5e, 0xe9, 0x3f,
	0xd3, 0xc1, 0xd1, 0x84, 0x89, 0xf2, 0xad, 0x2f, 0x01, 0xca, 0xeb, 0x9a, 0x69, 0xee, 0xc7, 0xcb,
	0x89, 0xfe, 0x09, 0x7e, 0xb1, 0x61, 0xcf, 0xee, 0x3f, 0xce, 0x7e, 0x20, 0xbc, 0x77, 0xa1, 0x72,
	0xfb, 0x23, 0xee, 0xad, 0xd2, 0xf3, 0xc9, 0xa6, 0xa3, 0x25, 0xeb, 0x41, 0xb8, 0xaf, 0x77, 0x7b,
	0x3a, 0x88, 0x2d, 0xf1, 0xd1, 0x7f, 0x41, 0xbd, 0xda, 0xf1, 0xfd, 0xca, 0xea, 0x86, 0x0f, 0xb6,
	0x76, 0xc4, 0x28, 0xba, 0x9d, 0x79, 0xe8, 0x6e, 0xe6, 0xa1, 0xdf, 0x33, 0x0f, 0x7d, 0x9b, 0x7b,
	0xd6, 0xdd, 0xdc, 0xb3, 0x7e, 0xce, 0x3d, 0xeb, 0x2a, 0xd8, 0x9a, 0xe9, 0x8d, 0xb9, 0x5a, 0x26,
	0xd9, 0x64, 0xdf, 0x00, 0xdf, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xcb, 0x20, 0x5d, 0x07,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SwapToIST(ctx context.Context, in *MsgSwapToIST, opts ...grpc.CallOption) (*MsgSwapToISTResponse, error)
	SwapToStablecoin(ctx context.Context, in *MsgSwapToStablecoin, opts ...grpc.CallOption) (*MsgSwapToStablecoinResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SwapToIST(ctx context.Context, in *MsgSwapToIST, opts ...grpc.CallOption) (*MsgSwapToISTResponse, error) {
	out := new(MsgSwapToISTResponse)
	err := c.cc.Invoke(ctx, "/onomyprotocol.psm.v1.Msg/SwapToIST", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SwapToStablecoin(ctx context.Context, in *MsgSwapToStablecoin, opts ...grpc.CallOption) (*MsgSwapToStablecoinResponse, error) {
	out := new(MsgSwapToStablecoinResponse)
	err := c.cc.Invoke(ctx, "/onomyprotocol.psm.v1.Msg/SwapToStablecoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SwapToIST(context.Context, *MsgSwapToIST) (*MsgSwapToISTResponse, error)
	SwapToStablecoin(context.Context, *MsgSwapToStablecoin) (*MsgSwapToStablecoinResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SwapToIST(ctx context.Context, req *MsgSwapToIST) (*MsgSwapToISTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwapToIST not implemented")
}
func (*UnimplementedMsgServer) SwapToStablecoin(ctx context.Context, req *MsgSwapToStablecoin) (*MsgSwapToStablecoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwapToStablecoin not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SwapToIST_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSwapToIST)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SwapToIST(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onomyprotocol.psm.v1.Msg/SwapToIST",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SwapToIST(ctx, req.(*MsgSwapToIST))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SwapToStablecoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSwapToStablecoin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SwapToStablecoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onomyprotocol.psm.v1.Msg/SwapToStablecoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SwapToStablecoin(ctx, req.(*MsgSwapToStablecoin))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onomyprotocol.psm.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SwapToIST",
			Handler:    _Msg_SwapToIST_Handler,
		},
		{
			MethodName: "SwapToStablecoin",
			Handler:    _Msg_SwapToStablecoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "onomyprotocol/psm/v1/tx.proto",
}

func (m *MsgSwapToIST) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSwapToIST) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSwapToIST) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Coin != nil {
		{
			size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSwapToISTResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSwapToISTResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSwapToISTResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSwapToStablecoin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSwapToStablecoin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSwapToStablecoin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.ToDenom) > 0 {
		i -= len(m.ToDenom)
		copy(dAtA[i:], m.ToDenom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ToDenom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSwapToStablecoinResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSwapToStablecoinResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSwapToStablecoinResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSwapToIST) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Coin != nil {
		l = m.Coin.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSwapToISTResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSwapToStablecoin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ToDenom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgSwapToStablecoinResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSwapToIST) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSwapToIST: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSwapToIST: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Coin == nil {
				m.Coin = &types.Coin{}
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSwapToISTResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSwapToISTResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSwapToISTResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSwapToStablecoin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSwapToStablecoin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSwapToStablecoin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSwapToStablecoinResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSwapToStablecoinResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSwapToStablecoinResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
